/**
 * `claude_session_uuid`, and the exact slice of Python's `uuid` module it needs.
 *
 * Interlock derives the `--session-id` it hands `claude` from the caller's S1
 * session id, as a **pure function of the id alone**:
 *
 * ```python
 * def claude_session_uuid(session_id: str) -> str:
 *     try:
 *         return str(uuid.UUID(session_id))
 *     except ValueError:
 *         return str(uuid.uuid5(SESSION_UUID_NAMESPACE, session_id))
 * ```
 *
 * Purity is the whole point of the design, not a stylistic preference: the
 * binding row is committed *before* the spawn, and a supervisor restarted with
 * nothing but the id has to arrive at the same UUID without asking a process
 * that may no longer exist. That makes cross-runtime agreement a correctness
 * property of this port rather than a nicety. If continuo derives a different
 * UUID than interlock for any id, the two disagree about which CLI session a
 * row names -- silently, because both answers are well-formed UUIDs.
 *
 * So this module is written as a **transcription of CPython**, not as "a UUIDv5
 * helper". Three things are transcribed, and each of them is a place a
 * reasonable JavaScript implementation diverges:
 *
 * 1. **RFC 4122 v5 itself** -- SHA-1 over `namespace.bytes + name.encode()`,
 *    the first 16 bytes taken big-endian, then the variant and version bits
 *    overwritten. The bit surgery runs on a `bigint`, because a `number`
 *    cannot hold 128 bits (this is rule 9's "which `number` parameters does the
 *    source type as `int`" question, answered: the only integer here is the
 *    128-bit value, and it is a `bigint` end to end).
 * 2. **`uuid.UUID(...)`'s leniency.** Python accepts far more than the
 *    canonical `8-4-4-4-12` spelling, and every accepted spelling is *honoured
 *    verbatim* rather than hashed -- so a port that rejects a spelling Python
 *    accepts does not merely refuse, it silently returns a **different UUID**.
 *    See {@link parsePythonUuid}.
 * 3. **`str(uuid.UUID(...))`'s canonicalisation** -- lowercase hex, canonical
 *    dash positions, and *no* normalisation of the version or variant nibbles.
 *    `uuid.UUID("ffffffffffffffffffffffffffffffff")` is not a v5 and is
 *    printed unchanged; a helper that "fixes" the version bits on parse would
 *    corrupt an id a caller chose deliberately.
 *
 * The one place this module is deliberately **narrower** than CPython is a
 * lone UTF-16 surrogate; see {@link uuid5}. Everything else was measured
 * against `python3` 3.12.3 rather than reasoned about, and the measurements are
 * pinned by `test/session/uuid5.test.ts` against literals generated by that
 * interpreter -- not by this implementation, which would prove nothing.
 *
 * Ported from interlock `src/claude_org_runtime/session/claude_cli_provider.py`
 * at `65f36c5` (`SESSION_UUID_NAMESPACE`, `claude_session_uuid`), plus
 * CPython 3.12's `Lib/uuid.py` and `Objects/longobject.c`. Nothing here spawns,
 * reads the clock or touches the filesystem, so nothing here goes through the
 * belt's runtime seam.
 *
 * @internal Not package API (D-0101). Never re-exported from `src/index.ts`.
 */

import { Buffer } from "node:buffer";
import { createHash } from "node:crypto";

// --------------------------------------------------------------------------
// Tables measured out of CPython
//
// These sit above the namespace constant below because that constant is
// computed at module load and reaches `CANONICAL_UUID`: a `const` declared
// later in the file is in its temporal dead zone at that moment, and the
// module would fail to load with a `ReferenceError`.
// --------------------------------------------------------------------------

/** Strict `8-4-4-4-12`, lowercase. Only ever applied to a namespace. */
const CANONICAL_UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/**
 * `Py_UNICODE_ISSPACE`, as `int()` sees it -- twenty-five code points,
 * enumerated by testing every code point in `range(0x110000)` on 3.12.3.
 *
 * It is **not** `str.isspace()`: `U+001C` through `U+001F` are whitespace to
 * `str.isspace` and are *not* stripped by `int()`, so a table derived from the
 * more obvious predicate would accept four inputs CPython refuses.
 */
const INT_WHITESPACE = new Set([
  0x0009, 0x000a, 0x000b, 0x000c, 0x000d, 0x0020, 0x0085, 0x00a0, 0x1680, 0x2000, 0x2001, 0x2002,
  0x2003, 0x2004, 0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200a, 0x2028, 0x2029, 0x202f, 0x205f,
  0x3000,
]);

/** The 68 `Nd` block bases. See {@link decimalDigitValue}. Ascending. */
const DECIMAL_BLOCK_STARTS = [
  0x00030, 0x00660, 0x006f0, 0x007c0, 0x00966, 0x009e6, 0x00a66, 0x00ae6, 0x00b66, 0x00be6, 0x00c66,
  0x00ce6, 0x00d66, 0x00de6, 0x00e50, 0x00ed0, 0x00f20, 0x01040, 0x01090, 0x017e0, 0x01810, 0x01946,
  0x019d0, 0x01a80, 0x01a90, 0x01b50, 0x01bb0, 0x01c40, 0x01c50, 0x0a620, 0x0a8d0, 0x0a900, 0x0a9d0,
  0x0a9f0, 0x0aa50, 0x0abf0, 0x0ff10, 0x104a0, 0x10d30, 0x11066, 0x110f0, 0x11136, 0x111d0, 0x112f0,
  0x11450, 0x114d0, 0x11650, 0x116c0, 0x11730, 0x118e0, 0x11950, 0x11c50, 0x11d50, 0x11da0, 0x11f50,
  0x16a60, 0x16ac0, 0x16b50, 0x1d7ce, 0x1d7d8, 0x1d7e2, 0x1d7ec, 0x1d7f6, 0x1e140, 0x1e2f0, 0x1e4f0,
  0x1e950, 0x1fbf0,
];

// --------------------------------------------------------------------------
// The two namespace constants
// --------------------------------------------------------------------------

/**
 * RFC 4122's URL namespace, `uuid.NAMESPACE_URL`.
 *
 * A literal rather than a derivation: CPython writes it as a literal too, and
 * there is nothing to derive it *from* -- it is one of the four constants the
 * RFC assigns.
 */
export const NAMESPACE_URL = "6ba7b811-9dad-11d1-80b4-00c04fd430c8";

/**
 * The name interlock hashes under {@link NAMESPACE_URL} to get its own
 * namespace. Exported separately from the namespace it produces so a reader can
 * see that the constant below is *computed*, byte for byte, the way the source
 * computes it -- rather than transcribed as a literal that would then have to
 * be trusted.
 */
export const SESSION_UUID_NAMESPACE_NAME =
  "https://github.com/suisya-systems/interlock/session-uuid";

/**
 * Namespace for deriving a `claude`-acceptable session UUID from an S1 id.
 *
 * Fixed, so the derivation is a pure function of the id alone. Computed at
 * module load exactly as `claude_cli_provider.py` computes it at import.
 */
export const SESSION_UUID_NAMESPACE: string = uuid5(NAMESPACE_URL, SESSION_UUID_NAMESPACE_NAME);

// --------------------------------------------------------------------------
// The two public functions
// --------------------------------------------------------------------------

/**
 * The `--session-id` value for one S1 session id, as a pure function.
 *
 * An id that already parses as a UUID -- in any spelling Python accepts -- is
 * honoured verbatim, canonicalised; anything else is mapped through
 * {@link SESSION_UUID_NAMESPACE}.
 *
 * The `typeof` guard has no counterpart in the source and is not a
 * generalisation: a non-`str` id already fails in Python, just less tidily --
 * `uuid.UUID(1)` raises `AttributeError: 'int' object has no attribute
 * 'replace'` and `uuid.UUID(None)` raises `TypeError`, measured on 3.12.3.
 * `claude_session_uuid` catches only `ValueError`, so both propagate out of it.
 * In TypeScript the parameter's declared type does not exclude
 * the value at runtime (rule 9), and the specific hazard is a boxed `String`
 * or any object with a `toString`: without the guard it would be coerced by
 * `replaceAll` and friends, and a `Symbol.toPrimitive` that answers differently
 * on successive reads would make this function impure -- which is the one
 * property it exists to have.
 */
export function claudeSessionUuid(sessionId: string): string {
  requireString(sessionId, "session id");
  return parsePythonUuid(sessionId) ?? uuid5(SESSION_UUID_NAMESPACE, sessionId);
}

/**
 * `str(uuid.UUID(text))`, or `undefined` where CPython raises `ValueError`.
 *
 * `undefined` rather than a thrown error because the source's control flow is
 * `try/except ValueError` around exactly this call, and a caller of this
 * function is always asking a question ("is this already a UUID?"), never
 * reporting a fault.
 *
 * CPython's parse, transcribed (`Lib/uuid.py`, `UUID.__init__`):
 *
 * ```python
 * hex = hex.replace('urn:', '').replace('uuid:', '')
 * hex = hex.strip('{}').replace('-', '')
 * if len(hex) != 32:
 *     raise ValueError('badly formed hexadecimal UUID string')
 * int = int_(hex, 16)
 * ```
 *
 * Four consequences that a hand-written `/^[0-9a-f]{8}-.../` check does not
 * have, all of them measured on 3.12.3 and all of them reachable from a
 * caller-chosen session id:
 *
 * - `'urn:'` and `'uuid:'` are removed **wherever they occur**, not just as a
 *   prefix, and only in that lowercase spelling: `URN:UUID:...` is refused.
 * - `strip('{}')` removes **any run** of `{` or `}` from either end, in any
 *   combination -- `}...{` parses, and so does `{{...}}`.
 * - Every `-` is removed, wherever it sits, so `1-2-3-...-f` parses. A leading
 *   `-` is removed too, which is why the sign this module's integer parse
 *   accepts is only `+`: a `-` can never survive to reach it.
 * - The remainder must be 32 characters **and a Python base-16 integer
 *   literal** -- which is a wider language than "32 hex digits". See
 *   {@link pythonHexIntegerLiteral}.
 *
 * The length is counted in **code points**, as Python's `len` counts it, not in
 * UTF-16 code units. The two differ for astral characters, and astral decimal
 * digits exist (`U+1D7CE` and its neighbours are `Nd`), so this is not an
 * academic distinction: a 32-code-point run of mathematical bold digits is a
 * string CPython parses and `text.length` would measure as 64.
 */
export function parsePythonUuid(text: string): string | undefined {
  requireString(text, "uuid text");

  // `replaceAll` matches Python's `str.replace`: all non-overlapping
  // occurrences, scanned left to right, with no re-scan of the replacement.
  // Both needles are ASCII, so neither can split a surrogate pair.
  const stripped = stripBraces(text.replaceAll("urn:", "").replaceAll("uuid:", "")).replaceAll(
    "-",
    "",
  );

  const codePoints = Array.from(stripped, (character) => character.codePointAt(0) as number);
  if (codePoints.length !== 32) {
    return undefined;
  }

  const value = pythonHexIntegerLiteral(transformDecimalAndSpaceToAscii(codePoints));
  if (value === undefined) {
    return undefined;
  }

  // CPython also checks `0 <= int < 1<<128` here. It is unreachable through
  // this path and so is deliberately not transcribed: the sign cannot be
  // negative (see above), and 32 characters cannot encode more than 32 hex
  // digits, which is exactly 2**128 - 1.
  return formatUuid(value);
}

/**
 * `uuid.uuid5(namespace, name)`, rendered as `str(...)` renders it.
 *
 * `namespace` is taken as a canonical UUID string rather than as an opaque
 * value: the only two namespaces in this belt are the constants above, and a
 * string keeps the module free of a UUID class that would exist solely to be
 * passed here. It is validated strictly -- *not* through
 * {@link parsePythonUuid} -- because a namespace is this port's own datum, not
 * a caller's id, and accepting `{...}` or a `urn:` prefix for it would be a
 * generalisation with no counterpart in the source.
 *
 * **The one deliberate narrowing in this module.** Python's
 * `bytes(name, "utf-8")` raises `UnicodeEncodeError` on a lone surrogate, so
 * interlock fails loudly. A JavaScript string can hold one, and both
 * `Buffer.from(s, "utf8")` and `TextEncoder` replace it with `U+FFFD` -- which
 * would map `"\ud800"`, `"\udc00"` and a literal `U+FFFD` to the **same** UUID. Three
 * distinct session ids sharing one CLI identity is a failure this function's
 * purity contract exists to prevent, and it is a failure interlock cannot have.
 * So a lone surrogate is refused here rather than silently folded. This is the
 * only input for which continuo throws where interlock throws a different
 * exception type, and it is recorded as a deviation rather than left to be
 * discovered.
 */
export function uuid5(namespace: string, name: string): string {
  requireString(namespace, "namespace");
  requireString(name, "name");
  if (!CANONICAL_UUID.test(namespace)) {
    throw new TypeError(
      `namespace must be a canonical lowercase UUID, got ${JSON.stringify(namespace)}`,
    );
  }

  const namespaceBytes = Buffer.from(namespace.replaceAll("-", ""), "hex");
  const digest = createHash("sha1")
    .update(Buffer.concat([namespaceBytes, encodeUtf8Strict(name)]))
    .digest();

  // `int.from_bytes(hash[:16])` -- big endian, which is `toString("hex")`.
  let value = BigInt(`0x${digest.subarray(0, 16).toString("hex")}`);
  // The four lines below are CPython's, verbatim. `bigint` bitwise operators
  // are two's complement over an unbounded width, so `~(0xc000n << 48n)` masks
  // exactly the two variant bits and nothing above them, as Python's does.
  value &= ~(0xc000n << 48n);
  value |= 0x8000n << 48n;
  value &= ~(0xf000n << 64n);
  value |= 5n << 76n;
  return formatUuid(value);
}

// --------------------------------------------------------------------------
// CPython's integer literal grammar, for base 16
// --------------------------------------------------------------------------

/**
 * `int(text, 16)`, restricted to what can reach it from {@link parsePythonUuid}.
 *
 * `int()` accepts a **literal**, not a digit run, and every part of that
 * literal fits inside the 32-character budget `uuid.UUID` imposes. All five
 * were measured accepted on 3.12.3, and each one changes the answer of
 * `claude_session_uuid` for an id a caller could plausibly choose -- the first
 * three are spellable in the `[A-Za-z0-9._-]` alphabet a session id needs
 * anyway in order to name a state directory:
 *
 * | input (32 chars)                   | CPython |
 * |------------------------------------|---------|
 * | `1_234567890abcdef1234567890abcde` | parses (underscores separate digits) |
 * | `0x34567890abcdef1234567890abcde1` | parses (base-16 prefix) |
 * | `+1234567890abcdef1234567890abcde` | parses (leading sign) |
 * | `\t1234567890abcdef1234567890abcde` | parses (surrounding whitespace) |
 * | `U+3000` + 31 hex digits           | parses (Unicode whitespace) |
 *
 * The grammar, as `long_from_string` implements it (whitespace already folded
 * to ASCII spaces by {@link transformDecimalAndSpaceToAscii}):
 *
 * ```
 * literal := WS* '+'? ( '0x' | '0X' ) '_'? DIGITS WS*
 *          | WS* '+'? DIGITS WS*
 * DIGITS  := hexdigit ( '_'? hexdigit )*
 * ```
 *
 * The underscore rule is the fiddly one and is easy to get one notch too
 * permissive: `0x_1` parses but `_1` does not, `1_2` parses but `1__2` and
 * `1_` do not. A leading `-` is not in the grammar above because
 * {@link parsePythonUuid} has already removed every `-` in the string; see its
 * documentation.
 */
function pythonHexIntegerLiteral(text: string): bigint | undefined {
  let start = 0;
  let end = text.length;
  while (start < end && isAsciiSpace(text[start] as string)) {
    start += 1;
  }
  while (end > start && isAsciiSpace(text[end - 1] as string)) {
    end -= 1;
  }

  if (start < end && text[start] === "+") {
    start += 1;
  }

  let prefixed = false;
  if (
    end - start >= 2 &&
    text[start] === "0" &&
    (text[start + 1] === "x" || text[start + 1] === "X")
  ) {
    start += 2;
    prefixed = true;
  }
  if (prefixed && start < end && text[start] === "_") {
    start += 1;
  }

  if (start >= end || !isHexDigit(text[start] as string)) {
    return undefined;
  }
  let digits = text[start] as string;
  start += 1;

  while (start < end) {
    if (text[start] === "_") {
      start += 1;
    }
    if (start >= end || !isHexDigit(text[start] as string)) {
      return undefined;
    }
    digits += text[start] as string;
    start += 1;
  }

  return BigInt(`0x${digits}`);
}

/**
 * `_PyUnicode_TransformDecimalAndSpaceToASCII`, the step `int()` runs before it
 * parses anything.
 *
 * Every code point below `127` is kept; Unicode whitespace becomes an ASCII
 * space; a Unicode decimal digit becomes the ASCII digit of the same value; and
 * anything else becomes `?`, which no later branch accepts. Transcribing it --
 * rather than treating "hex digits" as `[0-9a-fA-F]` -- is what makes
 * `U+3000` (ideographic space) and `U+0660` (Arabic-Indic zero) behave here
 * as they behave in interlock. The `< 127` boundary is CPython's own and puts
 * `U+007F` in the `?` branch.
 */
function transformDecimalAndSpaceToAscii(codePoints: readonly number[]): string {
  let out = "";
  for (const codePoint of codePoints) {
    if (codePoint < 127) {
      out += String.fromCodePoint(codePoint);
    } else if (INT_WHITESPACE.has(codePoint)) {
      out += " ";
    } else {
      const decimal = decimalDigitValue(codePoint);
      out += decimal < 0 ? "?" : String(decimal);
    }
  }
  return out;
}

/**
 * `Py_UNICODE_TODECIMAL`: the value of a Unicode decimal digit, or `-1`.
 *
 * Backed by the 68 block starts of general category `Nd`, enumerated from
 * `unicodedata` on the interpreter this module was measured against (Unicode
 * 15.0.0, shipped with Python 3.12.3). Every `Nd` block is exactly ten
 * consecutive code points whose values run `0..9`, which the generator
 * asserted; four blocks are adjacent to another (`U+1D7D8` and its
 * neighbours), which is why the base has to be looked up rather than found by
 * scanning backwards from the character.
 *
 * The table is pinned to *Python's* Unicode version on purpose, not to Node's:
 * Python is the oracle this port is checked against, and `\p{Nd}` in a
 * JavaScript regular expression answers from whatever ICU the runtime was
 * built with.
 */
function decimalDigitValue(codePoint: number): number {
  let low = 0;
  let high = DECIMAL_BLOCK_STARTS.length - 1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    const base = DECIMAL_BLOCK_STARTS[middle] as number;
    if (codePoint < base) {
      high = middle - 1;
    } else if (codePoint > base + 9) {
      low = middle + 1;
    } else {
      return codePoint - base;
    }
  }
  return -1;
}

// --------------------------------------------------------------------------
// Small shared pieces
// --------------------------------------------------------------------------

/** `'%032x' % value` split `8-4-4-4-12`, which is all `UUID.__str__` does. */
function formatUuid(value: bigint): string {
  const hex = value.toString(16).padStart(32, "0");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/**
 * `str.strip('{}')`: remove every leading and trailing `{` or `}`, in any
 * order and any number, and nothing from the middle.
 *
 * Indexing by UTF-16 code unit is safe here only because both characters are
 * ASCII, so neither can be half of a surrogate pair.
 */
function stripBraces(text: string): string {
  let start = 0;
  let end = text.length;
  while (start < end && (text[start] === "{" || text[start] === "}")) {
    start += 1;
  }
  while (end > start && (text[end - 1] === "{" || text[end - 1] === "}")) {
    end -= 1;
  }
  return text.slice(start, end);
}

/**
 * `bytes(name, "utf-8")`, which refuses a lone surrogate instead of replacing
 * it. See {@link uuid5} for why replacement is not an option here.
 */
function encodeUtf8Strict(name: string): Buffer {
  for (let index = 0; index < name.length; index += 1) {
    const unit = name.charCodeAt(index);
    if (unit >= 0xdc00 && unit <= 0xdfff) {
      throw new TypeError(`name contains a lone low surrogate at index ${index}`);
    }
    if (unit >= 0xd800 && unit <= 0xdbff) {
      const next = name.charCodeAt(index + 1);
      // `charCodeAt` past the end is NaN, and NaN fails both comparisons.
      if (!(next >= 0xdc00 && next <= 0xdfff)) {
        throw new TypeError(`name contains a lone high surrogate at index ${index}`);
      }
      index += 1;
    }
  }
  return Buffer.from(name, "utf8");
}

/**
 * The runtime half of a `string` parameter (rule 9).
 *
 * The message names the `typeof` and never the value: a rejected argument can
 * be anything at all, and this module's output has to stay ASCII (D-0006).
 */
function requireString(value: string, what: string): void {
  if (typeof value !== "string") {
    throw new TypeError(`${what} must be a string, got ${typeof value}`);
  }
}

function isAsciiSpace(character: string): boolean {
  return (
    character === " " ||
    character === "\t" ||
    character === "\n" ||
    character === "\v" ||
    character === "\f" ||
    character === "\r"
  );
}

function isHexDigit(character: string): boolean {
  return (
    (character >= "0" && character <= "9") ||
    (character >= "a" && character <= "f") ||
    (character >= "A" && character <= "F")
  );
}
