"""The Python half of the format-string differential vector.

``src/attention/pyformat.ts`` transcribes CPython's
``string.Formatter().parse``, ``str.format_map`` and ``str.__format__``,
because ``attention/notify.py``'s ``render_text`` runs a template the
OPERATOR wrote through all three. That makes their exact behaviour part
of the notification surface rather than an implementation detail of it:
a transcription that refuses a template CPython renders replaces the
operator's text with the English default, and one that renders a
template CPython refuses is the watcher crash the whole fallback path
exists to prevent.

The same argument the fnmatch/shlex vector makes applies here, and the
measurement bears it out rather than merely justifying it. Reviewing a
brace parser and a format mini-language by eye is the task human review
is worst at, and the first draft of this transcription -- written from
CPython's own source, not guessed at -- disagreed with CPython on FOUR
of the first fifty inputs. All four were found by running this script
against it, none by reading it.

This script emits the vector: for every template in
``parity/oracle/pyformat-corpus.json``, what CPython answers.
``test/attention/pyformat-oracle.test.ts`` rebuilds the same corpus in
the same order and asserts the transcription agrees at every position.

Not run in CI -- it needs no interlock checkout, but it does need
Python, and a vector the suite can regenerate for itself asserts nothing
(see ``docs/differential-oracle.md`` section 5). Run it by hand and
commit the result.

Usage, from the continuo repository root::

    python3 scripts/oracle/dump_pyformat.py parity/oracle/pyformat-vector.json

ASCII only: this file prints to stdout and the repository's output
policy (DECISIONS.md D-0006) applies to anything that reaches a console.
"""

from __future__ import annotations

import json
import platform
import string
import sys
from pathlib import Path

CORPUS = Path("parity/oracle/pyformat-corpus.json")


def placeholders(template: str) -> list[str]:
    """``notify._placeholders``, transcribed here rather than imported.

    Imported, this would need an interlock checkout on the path, and the
    vector is meant to be regenerable from continuo alone. The function
    is eight lines and is quoted verbatim from
    ``claude_org_runtime/attention/notify.py`` at ``65f36c5``.
    """
    out: set[str] = set()
    formatter = string.Formatter()
    try:
        for _, field_name, _, _ in formatter.parse(template):
            if not field_name:
                continue
            if "." in field_name or "[" in field_name:
                out.add("__invalid__")
                continue
            out.add(field_name)
    except ValueError:
        out.add("__invalid__")
    return sorted(out)


def render(template: str, values: dict[str, str]) -> dict[str, object]:
    """What ``render_text`` would learn about one template."""
    found = placeholders(template)
    unknown = sorted(set(found) - set(values))
    row: dict[str, object] = {
        "template": template,
        "placeholders": found,
        "unknown": unknown,
        "rendered": None,
        "error": None,
        "message": None,
    }
    if unknown:
        # render_text never formats a template with an unknown placeholder:
        # it warns and falls back before it gets there.
        return row
    try:
        row["rendered"] = template.format_map(values)
    except (ValueError, IndexError) as exc:
        # The two classes the source catches. The class is what decides
        # whether the watcher falls back or crashes; the message is
        # recorded too, because it reaches the operator's stderr.
        row["error"] = type(exc).__name__
        row["message"] = str(exc)
    return row


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: dump_pyformat.py <output.json>", file=sys.stderr)
        return 2
    corpus = json.loads(CORPUS.read_text(encoding="utf-8"))
    values = dict(corpus["values"])
    rows = [render(template, values) for template in corpus["templates"]]
    payload = {
        "$comment": (
            "Generated by scripts/oracle/dump_pyformat.py from "
            "parity/oracle/pyformat-corpus.json. Do not edit by hand. "
            "One row per template, in corpus order."
        ),
        "generator": {
            "python": platform.python_version(),
            "implementation": platform.python_implementation(),
        },
        "values": values,
        "rows": rows,
    }
    Path(argv[1]).write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(rows)} rows to {argv[1]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
