"""The Python half of the ``os.path`` differential vector.

``src/fencing/pypath.ts`` transcribes ``posixpath`` and ``ntpath`` because the
settings generator (``settings/generator.py``) is written in them and its
decisions turn on their exact answers: ``_is_inside_root`` composes
``normpath`` with an ``os.sep`` boundary test to decide whether a Layer 3 deny
entry escaped the sandbox read roots, and a kept structured entry reaches
``settings.local.json`` as the literal string ``os.path.join`` returned. A
transcription that is 99% right drops a deny entry the source keeps, or keeps
one the source drops, with no probe and no error to say so.

BOTH namespaces are dumped from one interpreter, on whatever platform runs this
script: ``ntpath`` is importable everywhere, and its answers do not depend on
the host. That is deliberate -- the port dispatches on ``process.platform``, so
a vector generated per platform would check each half only on the cells that
ship it, and the Windows half is the one this repository's matrix runs least.

Not run in CI -- a vector the suite can regenerate for itself asserts nothing
(``docs/differential-oracle.md`` section 5). Run it by hand and commit the
result.

Usage, from the continuo repository root::

    python3 scripts/oracle/dump_ospath.py parity/oracle/ospath-vector.json

ASCII only: this file prints to stdout and the repository's output policy
(DECISIONS.md D-0006) applies to anything that reaches a console.
"""

from __future__ import annotations

import json
import ntpath
import platform
import posixpath
import sys
from pathlib import Path
from typing import Any

CORPUS = Path("parity/oracle/ospath-corpus.json")


def _module_section(module: Any, corpus: dict) -> dict:
    paths = corpus["paths"]
    joins = corpus["joins"]
    return {
        "normpath": [module.normpath(p) for p in paths],
        "isabs": [module.isabs(p) for p in paths],
        "split": [list(module.split(p)) for p in paths],
        "splitdrive": [list(module.splitdrive(p)) for p in paths],
        "dirname": [module.dirname(p) for p in paths],
        "basename": [module.basename(p) for p in paths],
        "join": [module.join(*args) for args in joins],
    }


def main() -> None:
    corpus = json.loads(CORPUS.read_text(encoding="utf-8"))
    vector = {
        "$comment": (
            "Generated by scripts/oracle/dump_ospath.py. Do not edit by hand. "
            "See docs/differential-oracle.md."
        ),
        "python_version": platform.python_version(),
        "counts": {
            "paths": len(corpus["paths"]),
            "joins": len(corpus["joins"]),
        },
        "posixpath": _module_section(posixpath, corpus),
        "ntpath": _module_section(ntpath, corpus),
    }
    text = json.dumps(vector, indent=2) + "\n"
    if len(sys.argv) > 1:
        Path(sys.argv[1]).write_text(text, encoding="utf-8")
        sys.stdout.write(
            f"wrote {sys.argv[1]} "
            f"({len(corpus['paths'])} paths x 6 functions x 2 modules, "
            f"{len(corpus['joins'])} joins x 2 modules)\n"
        )
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
