/**
 * Single source of truth for the package version.
 *
 * Interlock has `claude_org_runtime/__about__.py` for the same reason and the
 * provenance header reads it there rather than carrying a literal: a report
 * states which build produced it, and a build that reported a version it is not
 * would be wrong in the one field a later reader uses to reproduce it
 * (`measurement-harness.md` section 6).
 *
 * A literal here rather than a read of `package.json`. The published package
 * has `dist/` at a different depth from `src/`, so a runtime read would resolve
 * differently in the two layouts and could fail in exactly the installed build
 * whose version the field is about. Instead the literal is pinned to
 * `package.json` by a test, so the two cannot drift apart silently.
 */
export const TOOL_VERSION = "0.0.0";

/**
 * What a build reports when it has no git information at all.
 *
 * A value rather than an absence, and that is the point: `--version` still
 * prints a well-formed line, so a host parsing it never faces an optional
 * field, and a reader can tell "this build does not know its revision" apart
 * from "this build forgot to print one".
 */
export const REVISION_UNKNOWN = "unknown";

/**
 * The alphabet a revision may use: a full commit, optionally marked dirty, or
 * {@link REVISION_UNKNOWN}.
 *
 * Full 40 hex rather than an abbreviation. Git's abbreviation length is a
 * function of repository size and of `core.abbrev`, so `--short` yields a value
 * that differs between two clones of the same commit -- and a build identifier
 * that depends on where it was built is not an identifier.
 *
 * `scripts/generate-revision.mjs` checks a derived revision against this
 * pattern BEFORE writing it into a module. That check is doing two jobs: it
 * keeps the generated bytes ASCII (`docs/cli-output-policy.md`, which cannot
 * see into `dist/` -- its scan skips that directory), and it closes a
 * code-injection seam, because an unvalidated string interpolated into
 * `export const BUILD_REVISION = "..."` is arbitrary JavaScript in a shipped
 * module. Nothing external ever reaches the value: no branch name, no tag, no
 * commit subject, no author -- all of which can be non-ASCII, and none of which
 * is part of a build's identity.
 */
export const REVISION_PATTERN = /^(?:[0-9a-f]{40}(?:-dirty)?|unknown)$/;

/**
 * The one line `--version` prints.
 *
 * A pure function of its three arguments so that the contract test has
 * something to assert against fixture inputs without naming the commit the
 * suite happens to be running at -- a test that pinned the current sha would
 * have to be edited by every rebase.
 *
 * The `(rev ...)` suffix is unconditional, including for
 * {@link REVISION_UNKNOWN}. The tempting shape -- elide the suffix when there
 * is nothing to say -- would make the field optional for every host that parses
 * this line, to save a word in the one case where the answer matters least.
 */
export function formatVersionLine(name: string, version: string, revision: string): string {
  return `${name} ${version} (rev ${revision})`;
}
